# Generated by Django 5.0.2 on 2024-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=40)),
                ('course_credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tutorial_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('att_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('course_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab'), ('Project', 'Project')], default='Theory', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_id', models.PositiveSmallIntegerField(unique=True)),
                ('year', models.CharField(choices=[('First', 'First Year 1st Semester'), ('First2', 'First Year 2nd Semester'), ('Second', 'Second Year 1st Semester'), ('Second2', 'Second Year 2nd Semester'), ('Third', 'Third Year 1st Semester'), ('Third2', 'Third Year 2nd Semester'), ('Fourth', 'Fourth Year 1st semster'), ('Fourth2', 'Fourth Year 2nd semster')], default='First', max_length=10)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='Enroll.course')),
            ],
        ),
    ]
